api/urls.py
from django.urls import path

app_name = 'api'
urlpatterns = []

carts/urls.py
from django.urls import path

from .views import cart_add, cart_decrement, cart_detail, cart_remove

app_name = 'carts'
urlpatterns = [
    path('detail/',cart_detail,name='detail'),
    path('add/<slug:product_slug>/',cart_add,name='add'),
    path('decrement/<slug:product_slug>/',cart_decrement,name='decrement'),
    path('remove/<int:item_pk>/',cart_remove,name='remove'),
]

orders/urls.py
from django.urls import path

from .views import(
    order_create,
)

app_name = 'orders'
urlpatterns = [
   path('create/',order_create,name='create'),
]

payments/urls.py
from django.urls import path

from .views import (
    create_checkout_session,
    payments_success,
    payments_cancel,
    stripe_webhook
)

app_name = 'payments'
urlpatterns = [
    path('cancel/',payments_cancel,name='cancel'),
    path('checkout/<int:pk>/',create_checkout_session,name='create-checkout-session'),
    path('success/',payments_success,name='success'),
    path('webhooks/stripe/',stripe_webhook,name='stripe-webhook'),
]

urshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

urlpatterns = [
    path('',home,name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls',namespace='api')),
    path('carts/',include('carts.urls',namespace = 'carts')),
    path('orders/',include('orders.urls',namespace = 'orders')),
    path('payments/',include('payments.urls',namespace = 'payments')),
    path('products/',include('products.urls',namespace = 'products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

orders/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.http import HttpRequest

from carts.models import Cart
from core.models import BaseModel
from core.utils import get_user_id

# Create your models here.
User = get_user_model()


class Address(BaseModel):

    BILLING = 'BILLING'
    SHIPPING = 'SHIPPING'

    ADDRESS_TYPES = (
        (BILLING, 'Billing address'),
        (SHIPPING, 'Shipping address'),
    )

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True)
    first_name = models.CharField(max_length=128, blank=True)
    last_name = models.CharField(max_length=128, blank=True)
    email = models.EmailField(blank=True)
    address_type = models.CharField(max_length=16,
                                    default=SHIPPING,
                                    choices=ADDRESS_TYPES)
    address_line_1 = models.CharField(max_length=128)
    address_line_2 = models.CharField(max_length=128, blank=True)
    country = models.CharField(max_length=128)
    state = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=128)
    zip = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = 'Addresses'


class OrderManager(models.Manager):

    def get_or_new(self, request: HttpRequest = None):
        """
            Get or create a new order object based on request
        """

        if request.user.is_authenticated:
            return self.model.objects.get_or_create(user=request.user)
        else:
            return self.model.objects.get_or_create(
                cart_id=get_user_id(request))


class Order(BaseModel):

    CREATED = 'CREATED'
    PAID = 'PAID'
    SHIPPED = 'SHIPPED'
    CANCELED = 'CANCELED'

    ORDER_STATUS = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (SHIPPED, 'Shipped'),
        (CANCELED, 'Canceled'),
    )
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True)
    order_id = models.CharField(max_length=128, blank=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    shipping_total = models.DecimalField(default=0.00,
                                         decimal_places=2,
                                         max_digits=10)
    # payment_type = models.CharField(max_lenght = 16,)
    status = models.CharField(max_length=16,
                              default=CREATED,
                              choices=ORDER_STATUS)

    objects = OrderManager()

orders/forms.py
from django import forms

from .models import Address, Order


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = [
            'first_name', 'last_name', 'email','address_type', 'address_line_1', 'address_line_2', 'country','state', 'city', 'zip'
        ]
        widgets = {
            'address_type': forms.Select(attrs={
                'class': 'form-select'}),
        }
class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = []

orders/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from carts.models import Cart
from core.utils import get_user_id

from .forms import AddressForm
from .models import Order

# Create your views here.


@login_required()
def order_create(request: HttpRequest):

    address_form = AddressForm()
    cart, _ = Cart.objects.get_or_new(request)
    context = {
        'address_form': address_form,
        'cart': cart,
        'items': cart.items.all(),
        'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY
    }

    if request.method == 'POST':

        address_form = AddressForm(request.POST)

        if address_form.is_valid():

            address = address_form.save(commit=False)
            address.user = request.user
            address.save()

            order = Order.objects.create(address=address, cart=cart)

            if request.user.is_authenticated:
                order.user = request.user
                order.save()

            return JsonResponse({
                'success': True,
            })

    return render(request, 'orders/order_create.html', context=context)

orders/templates/orders/order_create.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="checkout-page mt-100">
  <div class="container">
      <div class="checkout-page-wrapper">
          <div class="row">
              <div class="col-xl-9 col-lg-8 col-md-12 col-12">
                  <div class="section-header mb-3">
                      <h2 class="section-heading">Check out</h2>
                  </div>

                  <div class="checkout-progress overflow-hidden">
                      <ol class="checkout-bar px-0">
                          <li class="progress-step step-done"><a href="cart.html">Cart</a></li>
                          <li class="progress-step step-active"><a href="checkout.html">Your Details</a></li>
                          <li class="progress-step step-todo"><a href="checkout.html">Shipping</a></li>
                          <li class="progress-step step-todo"><a href="checkout.html">Payment</a></li>
                          <li class="progress-step step-todo"><a href="checkout.html">Review</a></li>
                      </ol>
                  </div>

                  <div class="checkout-user-area overflow-hidden d-flex align-items-center">
                      <div class="checkout-user-img me-4">
                          <img src="assets/img/checkout/user.jpg" alt="img">
                      </div>
                      <div class="checkout-user-details d-flex align-items-center justify-content-between w-100">
                          <div class="checkout-user-info">
                              <h2 class="checkout-user-name">Susan Gardner</h2>
                              <p class="checkout-user-address mb-0">2752 avenue Royale, Quebec, G1R 2B2, Canada</p>
                          </div>
                          
                          <a href="checkout.html#" class="edit-user btn-secondary">EDIT PROFILE</a>
                      </div>
                  </div>

                  <div class="shipping-address-area">
                      <h2 class="shipping-address-heading pb-1">Shipping address</h2>
                      <div class="shipping-address-form-wrapper">
                          <form action="" id="address-form" class="shipping-address-form common-form">
                            {% csrf_token %}
                              <div class="row">
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.first_name.label}}</label>
                                          {{address_form.first_name}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.last_name.label}}</label>
                                          {{address_form.last_name}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.email.label}}</label>
                                          {{address_form.email}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                    <fieldset>
                                      <label class="label">{{address_form.country.label}}</label>
                                      {{address_form.country}}
                                    </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                    <fieldset>
                                      <label class="label">{{address_form.state.label}}</label>
                                      {{address_form.state}}
                                    </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.city.label}}</label>
                                          {{address_form.city}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.address_type.label}}</label>                                                        
                                          {{address_form.address_type}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.zip.label}}</label>
                                          {{address_form.zip}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.address_line_1.label}}</label>
                                          {{address_form.address_line_1}}
                                      </fieldset>
                                  </div>
                                  <div class="col-lg-6 col-md-12 col-12">
                                      <fieldset>
                                          <label class="label">{{address_form.address_line_2.label}}</label>
                                          {{address_form.address_line_2}}
                                      </fieldset>
                                  </div>
                              </div>

                          </form>
                      </div>
                  </div>

                  <div class="shipping-address-area billing-area">
                      <h2 class="shipping-address-heading pb-1">Billing address</h2>
                      <div class="form-checkbox d-flex align-items-center mt-4">
                          <input class="form-check-input mt-0" type="checkbox">
                          <label class="form-check-label ms-2">
                              Same as shipping address
                          </label>
                      </div>
                  </div>
                  <div class="shipping-address-area billing-area">
                      <div class="minicart-btn-area d-flex align-items-center justify-content-between flex-wrap">
                          <a href={% url 'carts:detail' %} class="checkout-page-btn minicart-btn btn-secondary">BACK TO CART</a>
                          <button id="checkout-button" class="checkout-page-btn minicart-btn btn-primary">PROCEED TO PAYMENT</button>
                      </div>
                  </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-12 col-12">
                  <div class="cart-total-area checkout-summary-area">
                      <h3 class="d-none d-lg-block mb-0 text-center heading_24 mb-4">Order summary</h4>
                        {% for item in items %}
                          <div class="minicart-item d-flex">
                              <div class="mini-img-wrapper">
                                  <img class="mini-img" src={{item.preview}} alt={{item.product}}>
                              </div>
                              <div class="product-info">
                                  <h2 class="product-title"><a href="checkout.html#">{{item.product}}</a></h2>
                                  <p class="product-vendor">${{item.price}} x {{item.quantity}}</p>
                              </div>
                          </div>
                        {% endfor %}
                      <div class="cart-total-box mt-4 bg-transparent p-0">
                          <div class="subtotal-item subtotal-box">
                              <h4 class="subtotal-title">Subtotals:</h4>
                              <p class="subtotal-value">${{cart.total}}</p>
                          </div>
                          <div class="subtotal-item shipping-box">
                              <h4 class="subtotal-title">Shipping:</h4>
                              <p class="subtotal-value">$0.00</p>
                          </div>
                          <div class="subtotal-item discount-box">
                              <h4 class="subtotal-title">Discount:</h4>
                              <p class="subtotal-value">$0.00</p>
                          </div>
                          <hr />
                          <div class="subtotal-item discount-box">
                              <h4 class="subtotal-title">Total:</h4>
                              <p class="subtotal-value">${{cart.total}}</p>
                          </div>


                          <div class="mt-4 checkout-promo-code">
                              <input class="input-promo-code" type="text" placeholder="Promo code" />
                              <a href="#" class="btn-apply-code position-relative btn-secondary text-uppercase mt-3">
                                  Apply Promo Code
                              </a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}

{% block js %}


    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      // Create an instance of the Stripe object with your publishable API key
      const stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
      const checkoutButton = document.getElementById("checkout-button");
      const addressForm = document.getElementById('address-form');
      
      checkoutButton.addEventListener("click", function (e) {
        e.preventDefault()

        const addressFormData = new FormData(addressForm);

        fetch("{% url 'orders:create' %}",{
          method: 'POST',
          body: addressFormData
        })
        .then(function (response){
            return response.json();
        })
        .then(function (json_response){
            if (json_response.success){
              fetch("{% url 'payments:create-checkout-session' cart.pk %}", {
              method: "POST",
              headers: {
                  'X-CSRFToken': csrftoken
              }
            })
              .then(function (response) {
                return response.json();
              })
              .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
              })
              .then(function (result) {
                // If redirectToCheckout fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using error.message.
                if (result.error) {
                  alert(result.error.message);
                }
              })
              .catch(function (error) {
                console.error("Error:", error);
              });
            }
        })
        .catch(error => {
            console.error('Error:', error);
        });
        
      });
    </script>
{% endblock js %}