accounts/urls.py
from django.urls import path

from .views import (
    UploadPpView,
    UserLoginView,
    delete_profile_view,
    edit_profile_view,
    logout_view,
    signup_view,
)

app_name = 'accounts'
urlpatterns = [
     path('delete_profile/',delete_profile_view,name='delete'),
    path('edit_profile/',edit_profile_view,name='edit'),
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',logout_view,name='logout'),
    path('upload_pp/',UploadPpView.as_view(),name='upload-pp'),
    path('signup/',signup_view,name='signup')
]

api/urls.py
from django.urls import path

app_name = 'api'
urlpatterns = []

urshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

urlpatterns = [
    path('',home,name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls',namespace='api')),
    path('carts/',include('carts.urls',namespace = 'carts')),
    path('orders/',include('orders.urls',namespace = 'orders')),
    path('payments/',include('payments.urls',namespace = 'payments')),
    path('products/',include('products.urls',namespace = 'products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_save

from core.utils import thumbnail_image

# Create your models here.

class User(AbstractUser):

    SHOPPER = 'SHOPPER'
    SELLER = 'SELLER'

    USER_TYPE = (
        (SHOPPER, 'Shopper'),
        (SELLER, 'Seller'),
    )
    picture = models.ImageField(upload_to = 'users/',blank = True)
    type = models.CharField(max_length = 16 ,choices = USER_TYPE, default = SHOPPER)


    def __str__(self) -> str:
        return self.username


def user_pre_save(instance,sender,*args, **kwargs):
    ...

pre_save.connect(user_pre_save,sender = User)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()

class LoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = '__all__'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

class PpUploadForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['picture'].widget = forms.FileInput(
            attrs={'class':'form-control-file','value':''},
            )
            
    class Meta:
        model = User
        fields = ['picture']

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

accounts/views.py
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import UpdateView

from carts.models import Cart

from .forms import EditProfileForm, LoginForm, PpUploadForm, SignUpForm

User = get_user_model()

class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_success_url(self):
        return reverse('home')
    
    def form_valid(self, form):
        # Grab the session cart and assign it to the user
        guess_cart, _ = Cart.objects.get_or_new(self.request)
        user = form.get_user()
        # set user backend to the default to avoid multiple
        # authentication backends conflict
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request,user)
        user_cart, _ = Cart.objects.get_or_new(self.request)
        for item in guess_cart.items.all():
            item.cart = user_cart
            item.save()
        
        guess_cart.delete()
        return super().form_valid(form)

class UploadPpView(UpdateView):
    model = User
    form_class = PpUploadForm
    template_name = 'accounts/upload_profile_picture.html'

    def get_success_url(self):
        return reverse('home')

    def get_object(self):
        return self.request.user


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect(reverse('accounts:login'))
    return render(request,'accounts/logout.html')


def signup_view(request):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            # set user backend to the default to avoid multiple authentication backends conflict
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request,user)
            return redirect(reverse('accounts:upload-pp'))

    return render(request,'accounts/signup.html',context={'form':form})

def edit_profile_view(request):
    user = request.user
    form = EditProfileForm(instance=user)
    if request.method == 'POST':
        form = EditProfileForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
            return redirect(reverse('home'))
    context = {
        'form' : form
    }

    return render(request,'accounts/edit_profile.html',context=context)

def delete_profile_view(request):
    user = request.user
    if request.method == 'POST':
        user.delete()
        return redirect(reverse('accounts:login'))

    return render(request,'accounts/delete_profile.html',context={})

accounts/templates/accounts/delete_profile.html
{% extends '_base.html' %}

{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        <p>Are you sure you wanna delete your account?</p>
        <p>All your data will be definitely deteted.</p>
        <button type='submit'>Yes, delete</button>
    </form>
{% endblock content %}

accounts/templates/accounts/edit_profile.html
{% extends '_base.html' %}

{% block content %}

    {% if request.user.is_authenticated %}
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Update</button>
            <a href={% url 'accounts:delete' %}>Delete profile</a>
        </form>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/login.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block css %}
    
{% endblock css %}

{% block content %}
    <div class="login-page mt-100">
        <div class="container">
            {% if not request.user.is_authenticated %}
            <form action="" method="post" class="login-form common-form mx-auto">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="section-header mb-3">
                    <h2 class="section-heading text-center">Login</h2>
                </div>
                <div class="row">
                    <div class="col-12">
                        <fieldset>
                            <label for="{{ form.username.id_for_label }}">Username</label>
                            {{ form.username.errors }}
                            {{ form.username }}
                        </fieldset>
                    </div>
                    <div class="col-12">
                        <fieldset>
                            <label for="{{ form.password.id_for_label }}">Password</label>
                            {{ form.password }}
                        </fieldset>
                    </div>
                    <div class="col-12 mt-3">
                        <a href="#" class="text_14 d-block">Forgot your password?</a>
                        <button type="submit" class="btn-primary d-block mt-4 btn-signin">LOGIN</button>
                        <a href={% url 'accounts:signup' %} class="btn-secondary mt-2 btn-signin">CREATE AN ACCOUNT</a>
                    </div>
                </div>
            </form>
            {% else %}
                <p class="text_14 text-center">You are already logged in. Do you wanna <a href={% url 'accounts:logout' %}>logout</a>?</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block js %}
            <script>
                
            </script>
{% endblock js %}

accounts/templates/accounts/logout.html
{% extends '_base.html' %}

{% block content %}
<div class="login-page mt-100">
   <div class="container">
       <form action="" method='post' class="login-form common-form mx-auto">
         {% csrf_token %}
           <div class="section-header mb-3">
               <h2 class="section-heading text-center">Logout</h2>
           </div>
           <div class="row">
               <div class="col-12 mt-3">
                   <p class="text_16 text-center">Are you sure you wanna logout?</p>
                   <button type="submit" class="btn-primary d-block mt-4 btn-signin">LOGOUT</button>
               </div>
           </div>
       </form>
   </div>
</div>
  
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends '_base.html' %}

{% block content %}

    {% if request.user.is_authenticated %}
        
    {% endif %}
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends '_base.html' %}
{% load static %}

{% block css %}
    
{% endblock css %}

{% block content %}
<div class="login-page mt-100">
    <div class="container">
        {% if not request.user.is_authenticated %}
        <form action="" method="post" class="login-form common-form mx-auto">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="section-header mb-3">
                <h2 class="section-heading text-center">Sign up</h2>
            </div>
            <div class="row">
                <div class="col-12">
                    <fieldset>
                        <label for="{{ form.username.id_for_label }}">Username</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                    </fieldset>
                </div>
                <div class="col-12">
                    <fieldset>
                        <label for="{{ form.password1.id_for_label }}">Password</label>
                        {{ form.password1 }}
                    </fieldset>
                </div>
                <div class="col-12">
                    <fieldset>
                        <label for="{{ form.password2.id_for_label }}">Confirm password</label>
                        {{ form.password2 }}
                    </fieldset>
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn-primary d-block mt-4 btn-signin">SIGN UP</button>
                    <a href={% url 'accounts:login' %} class="btn-secondary mt-2 btn-signin">LOGIN PAGE</a>
                </div>
            </div>
        </form>
        {% else %}
            <p class="text_14 text-center">You are already logged in. Do you wanna <a href={% url 'accounts:logout' %}>logout</a>?</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/upload_profile_picture.html
{% extends '_base.html' %}

{% block content %}
<div class="login-page mt-100">
    <div class="container">
        {% if request.user.is_authenticated %}
        <form action="" method='post' class="login-form common-form mx-auto" enctype='multipart/form-data'>
          {% csrf_token %}
            <div class="section-header mb-3">
                <h2 class="section-heading text-center">Logout</h2>
            </div>
            <div class="row">
                <div class="col-12">
                    <fieldset>
                        <p class="text_16 d-block">Add a profile photo?</p>
                        {{ form.picture.errors }}
                        {% if form.instance.picture  %}
                        <div class="mb-3">
                            <img src={{form.instance.picture.url}} class="rounded" alt="img">
                        </div>
                        {% endif %}
                        {{ form.picture }}
                    </fieldset>
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn-primary d-block mt-4 btn-signin">UPLOAD</button>
                </div>
            </div>
        </form>
        {% endif %}
    </div>
 </div>
{% endblock content %}