api/urls.py
from django.urls import path

app_name = 'api'
urlpatterns = []

orders/urls.py
from django.urls import path

from .views import(
    order_create,
)

app_name = 'orders'
urlpatterns = [
   path('create/',order_create,name='create'),
]

urshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

urlpatterns = [
    path('',home,name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls',namespace='api')),
    path('carts/',include('carts.urls',namespace = 'carts')),
    path('orders/',include('orders.urls',namespace = 'orders')),
    path('payments/',include('payments.urls',namespace = 'payments')),
    path('products/',include('products.urls',namespace = 'products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title> {% block title %}UrSHOP{% endblock title %}</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <!-- all css -->
        <style>
            :root {
                --primary-color: #F76B6A;
                --secondary-color: #F76B6A;

                --btn-primary-border-radius: 0.25rem;
                --btn-primary-color: #fff;
                --btn-primary-background-color: #F76B6A;
                --btn-primary-border-color: #F76B6A;
                --btn-primary-hover-color: #fff;
                --btn-primary-background-hover-color: #F76B6A;
                --btn-primary-border-hover-color: #F76B6A;
                --btn-primary-font-weight: 500;

                --btn-secondary-border-radius: 0.25rem;
                --btn-secondary-color: #00234D;
                --btn-secondary-background-color: transparent;
                --btn-secondary-border-color: #00234D;
                --btn-secondary-hover-color: #fff;
                --btn-secondary-background-hover-color: #F76B6A;
                --btn-secondary-border-hover-color: #F76B6A;
                --btn-secondary-font-weight: 500;

                --heading-color: #000;
                --heading-font-family: 'Poppins', sans-serif;
                --heading-font-weight: 700;

                --title-color: #000;
                --title-font-family: 'Poppins', sans-serif;
                --title-font-weight: 400;

                --body-color: #000;
                --body-background-color: #fff;
                --body-font-family: 'Poppins', sans-serif;
                --body-font-size: 14px;
                --body-font-weight: 400;

                --section-heading-color: #000;
                --section-heading-font-family: 'Poppins', sans-serif;
                --section-heading-font-size: 48px;
                --section-heading-font-weight: 600;

                --section-subheading-color: #000;
                --section-subheading-font-family: 'Poppins', sans-serif;
                --section-subheading-font-size: 16px;
                --section-subheading-font-weight: 400;
            }
        </style>

        <!-- CSS -->
        <link rel="stylesheet" href={% static 'css/vendor.css' %}>
        <link rel="stylesheet" href={% static 'css/style.css' %}>
        {% block css %}{% endblock css %} 
    </head>
<body>
    <div class="body-wrapper">
        {% include 'partials/announcement_bar.html' %}
        {% include 'partials/header.html' %}       
        <main id="MainContent" class="content-for-layout">
            {% block content %}
            {% endblock content %}
        </main>
        {% include 'partials/footer.html' %}
        <!-- scrollup start -->
        <button id="scrollup">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg>  
        </button>
        <!-- scrollup end -->
        {% include 'partials/drawer_menu.html' %}
        {% include 'partials/drawer_cart.html' %}
        {% include 'partials/product_quickview.html' %}
        {% block extras %}{% endblock extras %}
        <!-- all js -->
        <script src={% static 'js/vendor.js' %}></script>
        <script src={% static 'js/main.js' %}></script>
    </div>
    {% block js %}
    {% endblock js %}
</body>
</html>

templates/home.html
{% extends '_base.html' %}

{% block content %}
  {% include 'partials/slideshow.html' %}
  {% include 'partials/trusted_badges.html' %}
  {% include 'partials/collection.html' %}
  {% include 'partials/banner.html' %}
  {% include 'partials/featured_collection.html' %}
  {% include 'partials/single_banner.html' %}
  {% include 'partials/instagram.html' %}
  {% include 'partials/newsletter.html' %}
{% endblock content %}

{% block extras %}
{% endblock extras %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UrSHOP</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href={% url 'products:create' %}>Create</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}
</body>
</html>