api/urls.py
from django.urls import path

app_name = 'api'
urlpatterns = []

carts/urls.py
from django.urls import path

from .views import cart_add, cart_decrement, cart_detail, cart_remove

app_name = 'carts'
urlpatterns = [
    path('detail/',cart_detail,name='detail'),
    path('add/<slug:product_slug>/',cart_add,name='add'),
    path('decrement/<slug:product_slug>/',cart_decrement,name='decrement'),
    path('remove/<int:item_pk>/',cart_remove,name='remove'),
]

products/urls.py
from django.urls import path

from .views import (
    ProductCreateView,
    ProductListView,
    product_delete,
    product_detail,
    product_edit,
)

app_name = 'products'
urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('delete/<slug:slug>', product_delete, name='delete'),
    path('detail/<slug:slug>', product_detail, name='detail'),
    path('edit/<slug:slug>', product_edit, name='edit'),
    path('', ProductListView.as_view(), name='list'),
]

urshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

urlpatterns = [
    path('',home,name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls',namespace='api')),
    path('carts/',include('carts.urls',namespace = 'carts')),
    path('orders/',include('orders.urls',namespace = 'orders')),
    path('payments/',include('payments.urls',namespace = 'payments')),
    path('products/',include('products.urls',namespace = 'products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

products/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.urls import reverse

from core.models import BaseModel
from core.utils import delete_file, reverse_querystring, thumbnail_image

# Create your models here.

User = get_user_model()


class Category(BaseModel):
    name = models.CharField(max_length=128, unique=True)
    image = models.ImageField(upload_to='categories/originals/', blank=True)
    thumbnail = models.ImageField(upload_to='categories/thumbnails/',
                                  blank=True)
    slug = models.SlugField(max_length=128, blank=True, unique=True, null=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self) -> str:
        return self.name

    # def get_absolute_url(self):
    #     return reverse_querystring("products:list",query_kwargs={'category': self.slug})
    

    def save(self, *args, **kwargs):
        # if self.image:
        #     thumbnail_image(self)
        # qs = Category.objects.filter(name__iexact = self.name ).exclude(pk = self.pk)
        # if qs.exists():
        #     return qs.first()
        super().save(*args, **kwargs)



class Brand(BaseModel):
    name = models.CharField('brand-name', max_length=128)

    def save(self, *args, **kwargs):
        # qs = Brand.objects.filter(name__iexact = self.name )
        # if qs.exists():
        #     return qs.first()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Product(BaseModel):
    user = models.ForeignKey(User,
                             related_name='products',
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, blank=True, unique=True, null=True)
    brand = models.ForeignKey(Brand,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='products')
    categories = models.ManyToManyField(Category, related_name='products')
    description = models.TextField(default='Description here!')
    price = models.DecimalField(decimal_places=2, max_digits=15, default=9.99)
    old_price = models.DecimalField(decimal_places=2,
                                    max_digits=15,
                                    default=0,
                                    blank=True)
    quantity = models.IntegerField(
        default=1,
        validators=[
            MinValueValidator(0, message='Quantity must be greater than 0'),
        ])

    def __str__(self) -> str:
        return self.name
    
    def preview(self):
        return self.images.first().image.url

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})


class Image(BaseModel):
    title = models.CharField(max_length=128, blank=True)
    image = models.ImageField(upload_to='products/originals/')
    thumbnail = models.ImageField(upload_to='products/thumbnails/', blank=True)
    product = models.ForeignKey(Product,
                                related_name='images',
                                on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.product.name

def image_pre_save(instance, sender, *args, **kwargs):
    ...
    # thumbnail_image(instance)


pre_save.connect(image_pre_save, sender=Image)


def image_pre_delete(instance, sender, *args, **kwargs):
    ...
    # delete_file(instance.image.path)
    # if instance.thumbnail:
    #     delete_file(instance.thumbnail.path)


pre_delete.connect(image_pre_delete, sender=Image)

products/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Brand, Category, Image, Product


class ProductForm(forms.ModelForm):
    """
        Form for product creation page with the necessary fields that will be completed with other related fields forms
    """

    class Meta:
        model = Product
        fields = [
            'name', 'categories', 'description', 'price', 'old_price',
            'quantity'
        ]

    def clean(self):
        data = self.cleaned_data

        name = data.get('name')
        description = data.get('description')

        qs = Product.objects.filter(name=name, description=description)
        if qs.exists():
            raise ValidationError(
                'A product with the same name and description already exists')

        return data


class CategoryForm(forms.ModelForm):
    """
        Category form to be used on category creation
    """

    class Meta:
        model = Category
        fields = ['name', 'description']


class BrandForm(forms.ModelForm):
    """
        Brand form to be used on product creation (with product form)
    """
    custom_names = {'name': 'brand-name'}

    def add_prefix(self, field_name):
        """
            Custom add_prefix to overwrite the name attribute ('name') of the input form to 'brand-name' in order to avoid conflict with product's name input form during product creation
        """
        field_name = self.custom_names.get(field_name, field_name)
        return super().add_prefix(field_name)

    class Meta:
        model = Brand
        fields = ['name']
        # widgets = {
        #     'name' : forms.TextInput(attrs={
        #         'name' : 'brand-name'
        #     })
        # }


class ImageForm(forms.ModelForm):
    """
        Image form to be used in addition with product form (only image needed)
    """

    class Meta:
        model = Image
        fields = ['image']

products/views.py
from django.forms import formset_factory
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, TemplateView

from .forms import BrandForm, ImageForm, ProductForm
from .models import Brand, Category, Product


class ProductCreateView(TemplateView):
    template_name = 'products/product_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_form'] = ProductForm()
        context['brand_form'] = BrandForm()
        context['image_form_set'] = formset_factory(ImageForm, extra=3)
        return context

    def post(self, request, *args, **kwargs):
        product_form = ProductForm(request.POST)
        image_form_set = formset_factory(ImageForm, extra=3)(request.POST,
                                                             request.FILES)
        brand_form = BrandForm(request.POST)

        if all([
                product_form.is_valid(),
                image_form_set.is_valid(),
                brand_form.is_valid()
        ]):
            product = product_form.save(commit=False)
            brand = brand_form.save()
            product.user = request.user
            product.brand = brand
            product.save()

            for image_form in image_form_set:
                if image_form.cleaned_data:
                    image = image_form.save(commit=False)
                    image.product = product
                    image.save()

            return redirect(product.get_absolute_url())


def product_detail(request: HttpRequest, slug: str) -> HttpResponse:
    product = get_object_or_404(Product.objects.prefetch_related('images'),
                                slug=slug)
    product_images = product.images.all()

    context = {
        'product': product,
        'main_image': product_images.first(),
        'product_images': product_images
    }
    return render(request,
                  template_name='products/product_detail.html',
                  context=context)


def product_edit(request: HttpRequest, slug: str) -> HttpResponse:
    ...


def product_delete(request: HttpRequest, slug: str) -> HttpResponse:

    product = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        product.delete()
        return HttpResponse('Product deleted successfully')
    return render(request, 'products/product_delete.html')


class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        category = self.request.GET.get('category')
        brand = self.request.GET.get('brand')
        if category:
            queryset = queryset.filter(category__slug__icontains=category)
        if brand:
            queryset = queryset.filter(brand__name__icontains=brand)
        return queryset

products/templates/products/create_product.html
{% extends '_base.html' %}

{% block title %}Create product{% endblock title %}
{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{product_form.as_p}}
        {{brand_form.as_p}}
        {{image_form_set.as_p}}
        
        <button type="submit">Create</button>
    </form>

{% endblock content %}

products/templates/products/product_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create product{% endblock title %}
{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{product_form|crispy}}
        {{brand_form|crispy}}
        {{image_form_set|crispy}}
        
        <button class='btn btn-success' type="submit">Create</button>
    </form>

{% endblock content %}

products/templates/products/product_delete.html
{% extends '_base.html' %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you wanna delete this product?</p>
        <button type="submit">Yes,delete</button>
    </form>
{% endblock content %}

products/templates/products/product_detail.html
{% extends '_base.html' %}

{% block css %}
    <style>
        .card
        {
            border:none;
        }
        .product
        {
            background-color: #eee
        }
        .brand
        {
            font-size: 13px
        }

        .price
        {
            color:var(--bs-primary);
            font-weight: bold;
        }
        .color
        {
            margin-bottom:10px;
        }
        label.radio
        {
            cursor: pointer;
        }
        label.radio input
        {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none;
        }
        label.radio span
        {
            padding: 2px 9px;
            border: 2px solid var(--bs-primary);
            display: inline-block;
            color: var(--bs-primary);
            border-radius: 3px;
            text-transform: uppercase;
        }
        label.radio input:checked+span
        {
            border-color: var(--bs-primary);
            background-color: var(--bs-primary);
            color: #fff;
        }
        .cart i
        {
            margin-right: 10px;
        }
    </style>
{% endblock css %}

{% block content %}

    <article>
        <div class="container mt-5 mb-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-10">
                    <div class="card">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="images p-3">
                                    <div class="text-center p-4"> 
                                        <img id="main-image" src={{main_image.image.url}} width="250"/> 
                                    </div>
                                    <div class="thumbnail text-center">
                                        {% for product_image in product_images %}
                                            <img src={{product_image.image.url}} width="70">
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="product p-4">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                                    </div>
                                    <div class="mt-4 mb-3">
                                        <span class="text-uppercase text-muted brand">
                                            {% if product.brand %}
                                                {{product.brand}}
                                            {% endif %}
                                        </span>
                                        <h5 class="text-uppercase">{{product.name}}</h5>
                                        <div class="price d-flex flex-row align-items-center">
                                            <span class="price">${{product.price}}</span>
                                            <div class="ml-2"> 
                                                <small class="text-danger fw-bold text-decoration-line-through old-price">
                                                {% if product.old_price %}
                                                    ${{product.old_price}}
                                                {% endif %}
                                                </small>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="description">{{product.description}}</p>
                                    <div class="sizes mt-5">
                                        <h6 class="text-uppercase">Size</h6> <label class="radio"> <input type="radio" name="size" value="S" checked> <span>S</span> </label> <label class="radio"> <input type="radio" name="size" value="M"> <span>M</span> </label> <label class="radio"> <input type="radio" name="size" value="L"> <span>L</span> </label> <label class="radio"> <input type="radio" name="size" value="XL"> <span>XL</span> </label> <label class="radio"> <input type="radio" name="size" value="XXL"> <span>XXL</span> </label>
                                    </div>
                                    <div class="cart mt-4 align-items-center"> 
                                        <a href={% url 'carts:add' product.slug %} class="btn btn-primary text-uppercase mr-2 px-4">
                                            Add to cart
                                        </a> 
                                        <i class="fa fa-heart text-muted"></i> 
                                        <i class="fa fa-share-alt text-muted"></i> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href={% url 'products:edit' product.slug %}>Edit</a>
        <a href={% url 'products:delete' product.slug %}>Delete</a>
    </article>
{% endblock content %}

{% block js %}
    <script>
        const thumbnail = document.querySelector('.thumbnail');
        
        for (const img of thumbnail.children) {

            img.addEventListener('click', function(e) {
                const mainImage = document.getElementById('main-image');
                mainImage.setAttribute('src',e.target.getAttribute('src'));
            }
            );
        }
    </script>
{% endblock js %}

products/templates/products/product_list.html
{% extends '_base.html' %}
{% load static %}

{% block css %}
<style>
    
</style>
{% endblock css %}

{% block content %}
<div class="collection mt-100">
  <div class="container">
      <div class="row flex-row-reverse">
          <!-- product area start -->
          <div class="col-lg-9 col-md-12 col-12">
              <div class="filter-sort-wrapper d-flex justify-content-between flex-wrap">
                  <div class="collection-title-wrap d-flex align-items-end">
                      <h2 class="collection-title heading_24 mb-0">All products</h2>
                      <p class="collection-counter text_16 mb-0 ms-2">(237 items)</p>
                  </div>
                  <div class="filter-sorting">
                      <div class="collection-sorting position-relative d-none d-lg-block">
                          <div
                              class="sorting-header text_16 d-flex align-items-center justify-content-end">
                              <span class="sorting-title me-2">Sort by:</span>
                              <span class="active-sorting">Featured</span>
                              <span class="sorting-icon">
                                  <svg class="icon icon-down" xmlns="http://www.w3.org/2000/svg"
                                      width="24" height="24" viewBox="0 0 24 24" fill="none"
                                      stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round" class="feather feather-chevron-down">
                                      <polyline points="6 9 12 15 18 9"></polyline>
                                  </svg>
                              </span>
                          </div>
                          <ul class="sorting-lists list-unstyled m-0">
                              <li><a href="collection-left-sidebar.html#" class="text_14">Featured</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Best Selling</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Alphabetically, A-Z</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Alphabetically, Z-A</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Price, low to high</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Price, high to low</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Date, old to new</a></li>
                              <li><a href="collection-left-sidebar.html#" class="text_14">Date, new to old</a></li>
                          </ul>
                      </div>
                      <div class="filter-drawer-trigger mobile-filter d-flex align-items-center d-lg-none">
                          <span class="mobile-filter-icon me-2">
                              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                  viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                  stroke-linecap="round" stroke-linejoin="round" class="icon icon-filter">
                                  <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon>
                              </svg>
                          </span>
                          <span class="mobile-filter-heading">Filter and Sorting</span>
                      </div>
                    </div>
                </div>
                <div class="collection-product-container">
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 col-6" data-aos="fade-up" data-aos-duration="700">
                                <div class="product-card">
                                    <div class="product-card-img">
                                        <a class="hover-switch" href="collection-left-sidebar.html">
                                            <img class="secondary-img" src="{{ product.images.first.image.url }}" alt="{{product.name}}">
                                            <img class="primary-img" src="{{ product.images.last.image.url }}"
                                                alt="product-img">
                                        </a>

                                        <div class="product-badge">
                                            <span class="badge-label badge-percentage rounded">-44%</span>
                                        </div>

                                        <div
                                            class="product-card-action product-card-action-2 justify-content-center">
                                            <a href="collection-left-sidebar.html#quickview-modal" class="action-card action-quickview"
                                                data-bs-toggle="modal">
                                                <svg width="26" height="26" viewBox="0 0 26 26" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path
                                                        d="M10 0C15.5117 0 20 4.48828 20 10C20 12.3945 19.1602 14.5898 17.75 16.3125L25.7188 24.2812L24.2812 25.7188L16.3125 17.75C14.5898 19.1602 12.3945 20 10 20C4.48828 20 0 15.5117 0 10C0 4.48828 4.48828 0 10 0ZM10 2C5.57031 2 2 5.57031 2 10C2 14.4297 5.57031 18 10 18C14.4297 18 18 14.4297 18 10C18 5.57031 14.4297 2 10 2ZM11 6V9H14V11H11V14H9V11H6V9H9V6H11Z"
                                                        fill="#00234D" />
                                                </svg>
                                            </a>

                                            <a href="collection-left-sidebar.html#" class="action-card action-wishlist">
                                                <svg class="icon icon-wishlist" width="26" height="22"
                                                    viewBox="0 0 26 22" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path
                                                        d="M6.96429 0.000183105C3.12305 0.000183105 0 3.10686 0 6.84843C0 8.15388 0.602121 9.28455 1.16071 10.1014C1.71931 10.9181 2.29241 11.4425 2.29241 11.4425L12.3326 21.3439L13 22.0002L13.6674 21.3439L23.7076 11.4425C23.7076 11.4425 26 9.45576 26 6.84843C26 3.10686 22.877 0.000183105 19.0357 0.000183105C15.8474 0.000183105 13.7944 1.88702 13 2.68241C12.2056 1.88702 10.1526 0.000183105 6.96429 0.000183105ZM6.96429 1.82638C9.73912 1.82638 12.3036 4.48008 12.3036 4.48008L13 5.25051L13.6964 4.48008C13.6964 4.48008 16.2609 1.82638 19.0357 1.82638C21.8613 1.82638 24.1429 4.10557 24.1429 6.84843C24.1429 8.25732 22.4018 10.1584 22.4018 10.1584L13 19.4036L3.59821 10.1584C3.59821 10.1584 3.14844 9.73397 2.69866 9.07411C2.24888 8.41426 1.85714 7.55466 1.85714 6.84843C1.85714 4.10557 4.13867 1.82638 6.96429 1.82638Z"
                                                        fill="#00234D" />
                                                </svg>
                                            </a>

                                            <a href={% url 'carts:add' product.slug %} class="action-card action-addtocart">
                                                <svg class="icon icon-cart" width="24" height="26"
                                                    viewBox="0 0 24 26" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path
                                                        d="M12 0.000183105C9.25391 0.000183105 7 2.25409 7 5.00018V6.00018H2.0625L2 6.93768L1 24.9377L0.9375 26.0002H23.0625L23 24.9377L22 6.93768L21.9375 6.00018H17V5.00018C17 2.25409 14.7461 0.000183105 12 0.000183105ZM12 2.00018C13.6562 2.00018 15 3.34393 15 5.00018V6.00018H9V5.00018C9 3.34393 10.3438 2.00018 12 2.00018ZM3.9375 8.00018H7V11.0002H9V8.00018H15V11.0002H17V8.00018H20.0625L20.9375 24.0002H3.0625L3.9375 8.00018Z"
                                                        fill="#00234D" />
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-card-details">
                                        <ul class="color-lists list-unstyled d-flex align-items-center">
                                            <li><a href="javascript:void(0)"
                                                    class="color-swatch swatch-black active"></a></li>
                                            <li><a href="javascript:void(0)"
                                                    class="color-swatch swatch-cyan"></a></li>
                                            <li><a href="javascript:void(0)"
                                                    class="color-swatch swatch-purple"></a>
                                            </li>
                                        </ul>
                                        <h3 class="product-card-title">
                                            <a href="collection-left-sidebar.html">best wood furniture</a>
                                        </h3>
                                        <div class="product-card-price">
                                            <span class="card-price-regular">$1529</span>
                                            <span
                                                class="card-price-compare text-decoration-line-through">$1759</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
              </div>
              <div class="pagination justify-content-center mt-100">
                  <nav>
                      <ul class="pagination m-0 d-flex align-items-center">
                          <li class="item disabled">
                              <a class="link">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                                      viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                      stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                      class="icon icon-left">
                                      <polyline points="15 18 9 12 15 6"></polyline>
                                  </svg>
                              </a>
                          </li>
                          <li class="item"><a class="link" href="collection-left-sidebar.html#">1</a></li>
                          <li class="item active"><a class="link" href="collection-left-sidebar.html#">2</a></li>
                          <li class="item"><a class="link" href="collection-left-sidebar.html#">3</a></li>
                          <li class="item"><a class="link" href="collection-left-sidebar.html#">4</a></li>
                          <li class="item">
                              <a class="link" href="collection-left-sidebar.html#">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                                      viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                      stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                      class="icon icon-right">
                                      <polyline points="9 18 15 12 9 6"></polyline>
                                  </svg>
                              </a>
                          </li>
                      </ul>
                  </nav>
              </div>
          </div>
          <!-- product area end -->
          {% include 'partials/sidebar.html' %}
      </div>
  </div>
</div>
{% endblock content %}